UI enhancements
BuildFire/customerFeedbackPlugin pull request #46
Opened 2023-07-16 17:38 UTC by ibrahemomari

2023-07-16 20:42 UTC, mas-iota requested changes

2023-07-16 20:42 UTC, mas-iota commented on control/content/app.js
> +                .when('/chat/:encodedReview', {
- Use the framework's state to store the reviews collection.
- Then access the target review by sending its userId as a query parameter.
- Manage the framework's state (update/delete/create)

2023-07-16 20:42 UTC, mas-iota commented on control/content/app.js
> +                .when('/chat/:encodedReview', {
`/chat/:userId`

2023-07-16 20:42 UTC, mas-iota commented on control/content/app.services.js
> +              result.introduction = '';
replace `result.introduction = '';` to `result.data.introduction = '';`

2023-07-16 20:42 UTC, mas-iota commented on control/content/assets/style.css
> +.section__title {
change to `section-title`

2023-07-16 20:42 UTC, mas-iota commented on widget/controllers/widget.home.controller.js
> +                WidgetHome[key.split('.')[1]] = result;
add values to WidgetHome.translations or think of a better approach

2023-07-16 20:42 UTC, mas-iota commented on widget/controllers/widget.home.controller.js
> +            getStrings();
Make sure getStrings is not falling in racing conditions

2023-08-23 23:34 UTC, charkhaw approved these changes

2023-08-23 23:34 UTC, merged